In [1]:
import pandas as pd

In [2]:
pd.__version__

'3.0.5'

In [3]:
# !wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

In [4]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [5]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [6]:
df.fuel_type.unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [7]:
df.fuel_type.nunique()

3

In [8]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [9]:
df.isnull().sum().sum()

np.int64(1141)

In [10]:
df.head(10)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
5,2007,USA,Hybrid,Front-wheel drive,2,2290,6,266.0,4260,18.8,31.2
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
7,2005,USA,Gasoline,Front-wheel drive,4,2370,6,279.0,4090,17.4,30.2
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
9,2004,USA,Diesel,All-wheel drive,5,2330,6,280.0,4620,17.7,31.2

In [11]:
df.fuel_efficiency_mpg[df['origin'] == 'Asia'].max()

np.float64(41.2)

In [12]:
df.horsepower.median()

np.float64(254.0)

In [13]:
df.horsepower.mode()

0    252.0
Name: horsepower, dtype: float64

In [14]:
mode_power = df.horsepower.mode().item()
mode_acc = df.acceleration.mode().item()
print(mode_power, mode_acc)
values = {'horsepower': mode_power, 'acceleration': mode_acc}

df = df.fillna(value=values)

252.0 18.8

In [15]:
df.horsepower.median()

np.float64(252.0)

In [16]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,18.8,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,18.8,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [17]:
df_asia = df[df.origin == "Asia"]

df_asia = df_asia[['model_year', 'vehicle_weight']]

In [18]:
X = df_asia.head(7)
X

    model_year  vehicle_weight
2         1996            4240
6         1992            4310
8         1997            4230
10        1978            4420
15        2007            3950
16        2021            4750
22        2019            4450

In [19]:
import numpy as np

X = np.array(X)
X

array([[1996, 4240],
       [1992, 4310],
       [1997, 4230],
       [1978, 4420],
       [2007, 3950],
       [2021, 4750],
       [2019, 4450]])

In [20]:
XTX = np.dot(X.T, X)
XTX

array([[ 28041424,  60750580],
       [ 60750580, 131950500]])

In [21]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 1.39675281e-05, -6.43071025e-06],
       [-6.43071025e-06,  2.96830537e-06]])

In [22]:
np.dot(XTX, XTX_inv)

array([[ 1.00000000e+00,  2.40156389e-14],
       [-2.61266601e-14,  1.00000000e+00]])

In [23]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [24]:
w = np.dot(np.dot(XTX_inv, X.T), y)
w

array([0.2327492 , 0.13644777])

In [25]:
sum(w)

np.float64(0.3691969690492686)

In [26]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,18.8,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,18.8,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0